import type { Station } from "@/types";

export const mockStations: Station[] = [
  {
    id: "station-1",
    name: "Tashkent City Charger",
    address: "1 Navoi Street, Tashkent",
    latitude: 41.311081,
    longitude: 69.240562,
    type: "DC",
    ports: [
      { id: "p1-1", type: "CCS", powerKW: 50, status: "available", pricePerKWh: 2500 },
      { id: "p1-2", type: "CHAdeMO", powerKW: 50, status: "occupied", pricePerKWh: 2500 },
    ],
    operator: "ElectroCar",
    openingHours: "24/7",
  },
  {
    id: "station-2",
    name: "Mega Planet SuperCharge",
    address: "17 Zulfiyakhanum Street, Tashkent",
    latitude: 41.3357,
    longitude: 69.2883,
    type: "AC",
    ports: [
      { id: "p2-1", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1500 },
      { id: "p2-2", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1500 },
    ],
    operator: "UzCharge",
    openingHours: "08:00 - 22:00",
  },
  {
    id: "station-3",
    name: "Samarqand Darvoza Hybrid Point",
    address: "5A Samarqand Darvoza Street, Tashkent",
    latitude: 41.3195,
    longitude: 69.2288,
    type: "Hybrid",
    ports: [
      { id: "p3-1", type: "CCS", powerKW: 60, status: "out_of_order", pricePerKWh: 2800 },
      { id: "p3-2", type: "Type 2", powerKW: 11, status: "available", pricePerKWh: 1200 },
    ],
    operator: "ElectroCar",
    openingHours: "24/7",
  },
  {
    id: "station-4",
    name: "Airport Fast Charge",
    address: "Tashkent International Airport",
    latitude: 41.2579,
    longitude: 69.2821,
    type: "DC",
    ports: [
      { id: "p4-1", type: "CCS", powerKW: 120, status: "available", pricePerKWh: 3000 },
      { id: "p4-2", type: "CHAdeMO", powerKW: 50, status: "available", pricePerKWh: 2500 },
    ],
    operator: "ChargeNet",
    openingHours: "24/7",
  },
  {
    id: "station-5",
    name: "Yunusabad EcoCharge",
    address: "7 Amir Temur Avenue, Yunusabad District, Tashkent",
    latitude: 41.3450,
    longitude: 69.2880,
    type: "AC",
    ports: [
      { id: "p5-1", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1600 },
      { id: "p5-2", type: "Type 2", powerKW: 11, status: "occupied", pricePerKWh: 1400 }
    ],
    operator: "Tashkent Charge",
    openingHours: "24/7",
  },
  {
    id: "station-6",
    name: "Chilonzor QuickPower",
    address: "1 Lutfi Street, Chilonzor District, Tashkent",
    latitude: 41.2775,
    longitude: 69.2021,
    type: "DC",
    ports: [
      { id: "p6-1", type: "CCS", powerKW: 75, status: "available", pricePerKWh: 2900 }
    ],
    operator: "ElectroCar",
    openingHours: "07:00 - 23:00",
  },
  {
    id: "station-7",
    name: "Mirzo Ulugbek Innovation Hub EV",
    address: "22 Ibrat St, Mirzo Ulugbek District, Tashkent",
    latitude: 41.3220,
    longitude: 69.3300,
    type: "Hybrid",
    ports: [
      { id: "p7-1", type: "CHAdeMO", powerKW: 40, status: "out_of_order", pricePerKWh: 2000 },
      { id: "p7-2", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1500 }
    ],
    operator: "UzCharge",
    openingHours: "Mon-Fri 09:00 - 18:00",
  },
  {
    id: "station-8",
    name: "Sergeli Bazaar EV Point",
    address: "Sergeli Dehqon Bozori, Sergeli District, Tashkent",
    latitude: 41.2250,
    longitude: 69.2080,
    type: "AC",
    ports: [
      { id: "p8-1", type: "Type 1", powerKW: 7.4, status: "available", pricePerKWh: 1000 },
      { id: "p8-2", type: "Type 2", powerKW: 7.4, status: "available", pricePerKWh: 1000 }
    ],
    operator: "Local Power",
    openingHours: "06:00 - 20:00",
  },
  {
    id: "station-9",
    name: "Magic City Park Charger",
    address: "Magic City Park, Babur Street, Tashkent",
    latitude: 41.2922, // Approximate location
    longitude: 69.2487, // Approximate location
    type: "DC",
    ports: [
      { id: "p9-1", type: "CCS", powerKW: 75, status: "available", pricePerKWh: 2800 },
      { id: "p9-2", type: "CCS", powerKW: 75, status: "occupied", pricePerKWh: 2800 },
    ],
    operator: "ElectroCar",
    openingHours: "10:00 - 23:00",
  },
  {
    id: "station-10",
    name: "Next Shopping Mall AC Point",
    address: "Next Mall, Bobur Street, Yakkasaray District, Tashkent",
    latitude: 41.2865, // Approximate location
    longitude: 69.2495, // Approximate location
    type: "AC",
    ports: [
      { id: "p10-1", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1500 },
      { id: "p10-2", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1500 },
      { id: "p10-3", type: "Type 2", powerKW: 11, status: "out_of_order", pricePerKWh: 1400 },
    ],
    operator: "UzCharge",
    openingHours: "24/7",
  },
  {
    id: "station-11",
    name: "Grand Mir Hotel EV Stop",
    address: "2 Mirabad Street, Tashkent", // Grand Mir Hotel actual address
    latitude: 41.29801, // More precise for Grand Mir
    longitude: 69.26800, // More precise for Grand Mir
    type: "Hybrid",
    ports: [
      { id: "p11-1", type: "CCS", powerKW: 50, status: "available", pricePerKWh: 3000 },
      { id: "p11-2", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1800 },
    ],
    operator: "ChargeNet",
    openingHours: "24/7",
  },
  {
    id: "station-12",
    name: "Chorsu Bazaar Public Charging",
    address: "Near Chorsu Bazaar, Sagban Street, Old City, Tashkent",
    latitude: 41.3265, // Approximate for Chorsu Bazaar
    longitude: 69.2372, // Approximate for Chorsu Bazaar
    type: "AC",
    ports: [
      { id: "p12-1", type: "Type 1", powerKW: 7.4, status: "available", pricePerKWh: 1200 },
      { id: "p12-2", type: "Type 2", powerKW: 11, status: "available", pricePerKWh: 1300 },
      { id: "p12-3", type: "Type 2", powerKW: 7.4, status: "occupied", pricePerKWh: 1200 },
    ],
    operator: "Tashkent Charge",
    openingHours: "07:00 - 19:00",
  },
  // New stations start here
  {
    id: "station-13",
    name: "Uchtepa Central Charger",
    address: "15 Lutfikor Street, Uchtepa District, Tashkent",
    latitude: 41.2715,
    longitude: 69.1750,
    type: "DC",
    ports: [
      { id: "p13-1", type: "CCS", powerKW: 60, status: "available", pricePerKWh: 2700 },
      { id: "p13-2", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1600 },
    ],
    operator: "GreenVolt",
    openingHours: "24/7",
  },
  {
    id: "station-14",
    name: "Shaykhantahur Plaza AC",
    address: "Labzak Street, Shaykhantahur District, Tashkent",
    latitude: 41.3250,
    longitude: 69.2500,
    type: "AC",
    ports: [
      { id: "p14-1", type: "Type 2", powerKW: 11, status: "occupied", pricePerKWh: 1300 },
      { id: "p14-2", type: "Type 2", powerKW: 11, status: "available", pricePerKWh: 1300 },
    ],
    operator: "EVPointUz",
    openingHours: "09:00 - 21:00",
  },
  {
    id: "station-15",
    name: "Yashnobod Industrial Park DC",
    address: "Farg'ona Yo'li Street, Yashnobod District, Tashkent",
    latitude: 41.2770,
    longitude: 69.3350,
    type: "DC",
    ports: [
      { id: "p15-1", type: "CHAdeMO", powerKW: 50, status: "available", pricePerKWh: 2400 },
      { id: "p15-2", type: "CCS", powerKW: 100, status: "available", pricePerKWh: 3100 },
    ],
    operator: "SparkCharge",
    openingHours: "24/7",
  },
  {
    id: "station-16",
    name: "Bektemir Logistics Hub",
    address: "Bektemir Yo'li Street, Bektemir District, Tashkent",
    latitude: 41.2200,
    longitude: 69.3400,
    type: "Hybrid",
    ports: [
      { id: "p16-1", type: "CCS", powerKW: 40, status: "out_of_order", pricePerKWh: 2600 },
      { id: "p16-2", type: "Type 1", powerKW: 7.4, status: "available", pricePerKWh: 1100 },
    ],
    operator: "ElectroCar",
    openingHours: "Mon-Sat 06:00 - 22:00",
  },
  {
    id: "station-17",
    name: "Almazar University Charger",
    address: "Universitetskaya Street, Almazar District, Tashkent",
    latitude: 41.3500,
    longitude: 69.2000,
    type: "AC",
    ports: [
      { id: "p17-1", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1550 },
    ],
    operator: "UzCharge",
    openingHours: "07:00 - 23:00",
  },
  {
    id: "station-18",
    name: "Mirabad Elite Residence",
    address: "8 Nukus Street, Mirabad District, Tashkent",
    latitude: 41.2905,
    longitude: 69.2750,
    type: "AC",
    ports: [
      { id: "p18-1", type: "Type 2", powerKW: 11, status: "available", pricePerKWh: 1450 },
      { id: "p18-2", type: "Type 2", powerKW: 11, status: "available", pricePerKWh: 1450 },
    ],
    operator: "ChargeNet",
    openingHours: "24/7 (For residents and guests)",
  },
  {
    id: "station-19",
    name: "Yunusabad City Hospital EV",
    address: "Ahmad Donish Street, Yunusabad District, Tashkent",
    latitude: 41.3700,
    longitude: 69.2950,
    type: "DC",
    ports: [
      { id: "p19-1", type: "CCS", powerKW: 50, status: "available", pricePerKWh: 2750 },
    ],
    operator: "Tashkent Charge",
    openingHours: "24/7",
  },
  {
    id: "station-20",
    name: "Chilanzar Trade Center PowerUp",
    address: "Al-Khwarizmi Street, Chilanzar District, Tashkent",
    latitude: 41.2650,
    longitude: 69.2100,
    type: "Hybrid",
    ports: [
      { id: "p20-1", type: "CCS", powerKW: 75, status: "occupied", pricePerKWh: 3000 },
      { id: "p20-2", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1650 },
    ],
    operator: "GreenVolt",
    openingHours: "08:00 - 00:00",
  },
  {
    id: "station-21",
    name: "Buyuk Ipak Yuli Metro Charger",
    address: "Near Buyuk Ipak Yuli Metro, Mirzo Ulugbek District, Tashkent",
    latitude: 41.3100,
    longitude: 69.3380,
    type: "AC",
    ports: [
      { id: "p21-1", type: "Type 2", powerKW: 7.4, status: "available", pricePerKWh: 1250 },
      { id: "p21-2", type: "Type 2", powerKW: 7.4, status: "available", pricePerKWh: 1250 },
    ],
    operator: "EVPointUz",
    openingHours: "24/7",
  },
  {
    id: "station-22",
    name: "Botanical Garden Eco Point",
    address: "Bogishamol Street, near Botanical Garden, Tashkent",
    latitude: 41.3480,
    longitude: 69.3150,
    type: "DC",
    ports: [
      { id: "p22-1", type: "CHAdeMO", powerKW: 40, status: "available", pricePerKWh: 2300 },
    ],
    operator: "SparkCharge",
    openingHours: "09:00 - 19:00",
  },
  {
    id: "station-23",
    name: "TTZ Market FastCharge",
    address: "TTZ-4, Near Korzinka, Mirzo Ulugbek District, Tashkent",
    latitude: 41.3650,
    longitude: 69.3500,
    type: "DC",
    ports: [
      { id: "p23-1", type: "CCS", powerKW: 120, status: "available", pricePerKWh: 3200 },
    ],
    operator: "ElectroCar",
    openingHours: "24/7",
  },
  {
    id: "station-24",
    name: "Compass Mall HyperCharger",
    address: "Compass Mall, Farghana Yuli, Bektemir District, Tashkent",
    latitude: 41.2400,
    longitude: 69.3520,
    type: "DC",
    ports: [
      { id: "p24-1", type: "CCS", powerKW: 150, status: "available", pricePerKWh: 3500 },
      { id: "p24-2", type: "CCS", powerKW: 150, status: "available", pricePerKWh: 3500 },
    ],
    operator: "UzCharge",
    openingHours: "10:00 - 22:00",
  },
  {
    id: "station-25",
    name: "Sergeli Drive-In AC",
    address: "Yangi Sergeli Yo'li, Sergeli District, Tashkent",
    latitude: 41.2150,
    longitude: 69.2000,
    type: "AC",
    ports: [
      { id: "p25-1", type: "Type 1", powerKW: 7.4, status: "occupied", pricePerKWh: 1150 },
      { id: "p25-2", type: "Type 2", powerKW: 11, status: "available", pricePerKWh: 1350 },
    ],
    operator: "ChargeNet",
    openingHours: "24/7",
  },
  {
    id: "station-26",
    name: "National Park Green Energy",
    address: "Alisher Navoi National Park, Tashkent",
    latitude: 41.3080,
    longitude: 69.2350,
    type: "Hybrid",
    ports: [
      { id: "p26-1", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1700 },
      { id: "p26-2", type: "CCS", powerKW: 25, status: "out_of_order", pricePerKWh: 2000 }, // Lower power DC
    ],
    operator: "Tashkent Charge",
    openingHours: "06:00 - 23:00",
  },
  {
    id: "station-27",
    name: "Yakkasaray Business Center EV",
    address: "Shota Rustaveli Street, Yakkasaray District, Tashkent",
    latitude: 41.2800,
    longitude: 69.2600,
    type: "AC",
    ports: [
      { id: "p27-1", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1750 },
      { id: "p27-2", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1750 },
    ],
    operator: "GreenVolt",
    openingHours: "Mon-Fri 08:00 - 20:00",
  },
  {
    id: "station-28",
    name: "Tashkent TV Tower Viewpoint",
    address: "Amir Temur Street, near TV Tower, Tashkent",
    latitude: 41.3400,
    longitude: 69.2830,
    type: "DC",
    ports: [
      { id: "p28-1", type: "CCS", powerKW: 60, status: "available", pricePerKWh: 2850 },
    ],
    operator: "EVPointUz",
    openingHours: "10:00 - 22:00",
  },
  {
    id: "station-29",
    name: "Mirobod Dehqon Bozori Charger",
    address: "Nukus Street, Mirobod Bozori, Tashkent",
    latitude: 41.2855,
    longitude: 69.2800,
    type: "AC",
    ports: [
      { id: "p29-1", type: "Type 1", powerKW: 7.4, status: "available", pricePerKWh: 1050 },
      { id: "p29-2", type: "Type 2", powerKW: 7.4, status: "available", pricePerKWh: 1050 },
    ],
    operator: "SparkCharge",
    openingHours: "07:00 - 19:00",
  },
  {
    id: "station-30",
    name: "Gazeta Complex Power Stop",
    address: "Sharof Rashidov Avenue, Yunusobod District, Tashkent",
    latitude: 41.3150,
    longitude: 69.2700,
    type: "Hybrid",
    ports: [
      { id: "p30-1", type: "CCS", powerKW: 50, status: "available", pricePerKWh: 2950 },
      { id: "p30-2", type: "Type 2", powerKW: 11, status: "occupied", pricePerKWh: 1400 },
    ],
    operator: "ElectroCar",
    openingHours: "24/7",
  },
  {
    id: "station-31",
    name: "Gafur Gulyam Park Charger",
    address: "Near Gafur Gulyam Park, Chilanzar District, Tashkent",
    latitude: 41.2880,
    longitude: 69.2180,
    type: "AC",
    ports: [
      { id: "p31-1", type: "Type 2", powerKW: 22, status: "available", pricePerKWh: 1600 },
    ],
    operator: "UzCharge",
    openingHours: "24/7",
  },
  {
    id: "station-32",
    name: "Kukcha Mosque Area Charging",
    address: "Kukcha Darvoza Street, Shaykhantahur District, Tashkent",
    latitude: 41.3330,
    longitude: 69.2120,
    type: "DC",
    ports: [
      { id: "p32-1", type: "CHAdeMO", powerKW: 45, status: "available", pricePerKWh: 2350 },
    ],
    operator: "ChargeNet",
    openingHours: "08:00 - 20:00",
  }
];

